### ISSUE TITLE
Add ability to implement proper Google Play Store and Services (replacing the restricted implementations currently avaliable).

### ISSUE THREAD

**Issue by AshiVered** [MustardChef/MagiskOnGPGPC#1]
Hello.
I'm [@a9381](https://xdaforums.com/m/a9381.11833283/) from XDA.
I think (don't know for sure, I don't have root on GPFP to check it...) that spoofing the device name will solve the problem.
(Like I solved the problem in the Aurora store).
For example, by using this Magisk module.
https://github.com/cnrd/MagiskHide-Props-Config
thanks.

**Comment by MustardChef** [comment]
First I am focusing on getting Intel Native Bridge working. 
Without the arm to x86_64 translation layer working properly, there is no point on working on the Play Store, for the moment.

**Comment by admin-elvistrujanovic** [comment]
> First I am focusing on getting Intel Native Bridge working properly. 
> Without the arm to x86_64 translation layer working properly, there is no point on working on the Play Store.

Well at least give us methods of booting unofficial images or we need modified (patched) version of bios.bin for that

**Comment by MustardChef** [comment]
> > First I am focusing on getting Intel Native Bridge working properly.
> > Without the arm to x86_64 translation layer working properly, there is no point on working on the Play Store.
> 
> Well at least give us methods of booting unofficial images or we need modified (patched) version of bios.bin for that

There is a reason why I have not provided a method. 
It will get patched by Google.

**Comment by admin-elvistrujanovic** [comment]
> > > First I am focusing on getting Intel Native Bridge working properly.
> > > Without the arm to x86_64 translation layer working properly, there is no point on working on the Play Store.
> > 
> > 
> > Well at least give us methods of booting unofficial images or we need modified (patched) version of bios.bin for that
> 
> No point in modding Google Play Games and then it getting patched by Google. There are many examples of Google patching and banning stuff. An example being methods and device fingerprints used to bypass Play Integrity checks on rooted devices. Thus I have taken a cautious approach to this, by not providing the method for now.

If you're waiting Google to allow that kind of exploiting and being able to root, you will never be able to publish it publicly since Google hates rooting. And also, rooting community deserves to get PoC of available exploits to gain root somehow - and Google Play Games beta emulator sounds very interesting for this kind of stuff - and also it's an first emulator with ability to block unsigned images from booting at all.

**Comment by MustardChef** [comment]
Yes. I understand your point.
I will discuss this agenda with my team and decide on whether or not we should release it, or wait until the "To-Do" list is complete, or someone else releases a method.

**Comment by admin-elvistrujanovic** [comment]
> Yes. I understand your point.
> I will discuss this agenda with my team (me and my two friends) and decide on whether or not we should release it, or wait until the "To-Do" list is complete.
> 
> Rushing this matter will not do any of us any good. It always best to take such things step by step.

So... what they said - what you've decided

Will it's exploit be leaked (patched files that will allow unsigned images to boot), or we need to wait To Do list to be completed for that or simply as that due to legal reasons and to avoid problems with Google, this repo will be read-only and the project will never see the light of the world because of it's high illegality and risk that Google will never allow it to be spread to the internet.

Or you will secretly work on it and everyone interested in it can simply just mention you, give to you some private contact where the person will be invited to private group where it will be able to download the project and find out about the exploits used in it (it's also illegal but it have more chances to not be found by Google)

**Comment by MustardChef** [comment]
@admin-elvistrujanovic We are releasing it once Google Play is fully working.

**Comment by admin-elvistrujanovic** [comment]
> @admin-elvistrujanovic 
> We are releasing it once Google Play is fully working. Ideally it will be public or semi-public, so we won't keep it a secret or gatekeep it from anyone.
> 
> Keep it mind that this decision could change at anytime.
> 
> This repo will only contain a program that will help you patch your Google Play Games client, and so we will not include any code from the emulator, hence this repo is under the AGPL v3 license. 
> 
> Yes, there is also some concern over the legality of this project. Google could take this repo down if they wanted to and there is a risk that the it could happen anytime before or after the files become available. We may need to make the project private, if so.

Can you tell me what you've tried with Google Play Services and it didn't work - maybe I can also help you with that - I can try something, put the changes in the magisk module and send it to you and we will see how the emulation software will react on that - I would love to help if I can of course (if the help is wanted) for Google Play Services full support (for root I cannot help too much except to try other root managers based on magisk and little tweaks to make root working better and boost performance of the emulator, but with modding already rooted emulator I could help)


There is also another way that could be much better than magisk modules and more permanent and I will also try that and send it to you if you want (modified system and vendor images)


And also if the project is private, there is always a way how to distribute private project to people who are interested without triggering Google to take an action (more secure to avoid legal action) so probably private sharing could have more luck than public sharing but we will see what will happen as soon this project gets prepared for public use 👍

**Comment by MustardChef** [comment]
I have tried a variety of things, none of which have worked.

1. Changing Device Props
2. Flashing Systemless Gapps Magisk Module
3. Manually adding GApps to System and Product .img files as per the recovery installation script.

**Comment by admin-elvistrujanovic** [comment]
> I have tried a variety of things to get GApps fully working, none of which have worked.
> 
> 1. Changing Device Props
> 2. Flashing Systemless Gapps Magisk Module
> 3. Manually adding GApps to System and Product .img files as per the recovery installation script.

What errors gives you when you do all of that

Any logs, VM logs, anything?

**Comment by MustardChef** [comment]
> > I have tried a variety of things to get GApps fully working, none of which have worked.
> > 
> > 1. Changing Device Props
> > 2. Flashing Systemless Gapps Magisk Module
> > 3. Manually adding GApps to System and Product .img files as per the recovery installation script.
> 
> What errors gives you when you do all of that
> 
> Any logs, VM logs, anything?

1. Props Changes do absolutely nothing and Play Store remains the same.
2. Systemless GApps module resets the whole GPGPC system
3. Every component starts crashing.

**Comment by admin-elvistrujanovic** [comment]
> > > I have tried a variety of things to get GApps fully working, none of which have worked.
> > > 
> > > 1. Changing Device Props
> > > 2. Flashing Systemless Gapps Magisk Module
> > > 3. Manually adding GApps to System and Product .img files as per the recovery installation script.
> > 
> > What errors gives you when you do all of that
> > 
> > Any logs, VM logs, anything?
> 
> 1. Props Changes do absolutely nothing and Play Store remains the same.
> 2. Flashing the Systemless GApps module, resets the whole GPGPC Android system
> 3. Every component starts crashing and eventually the Android system freezes.

Emulator probably have an type of protection against Google Play modifications - that's what could trigger emulator to deny systemless module and reset the system to default settings

As about for one option, yeah - that was expected for me since modding props only will not make all required configurations and missing API to be applied

As about the last one, it looks like that system itself (all parts of the core apps and etc...) have integrated set of APIs for that emulator that usually doesn't exist (or at least not all of them) in the standard Google Play bootstrap (services, cores, configurations...) - and also it could require more RAM allocations to work properly (and that means for some PCs reduced performances) and it could also be an implemented security mehanism in the system itself (in the random locations and apps in the system image so that it cannot be easy found and accessible) that if it detects standard Google Play Services, more APIs than usual and etc... it could freeze the device and probably even bootloop it.


So the last option could have more success but it requires much more time to probably make an custom version of GApps that have all APIs from this emulator and also other APIs too to support many services by Google, modify props and permission configuration in the system and vendor images to include APIs to the list and be sure that there is no conflicts between built-in Google APIs and custom GApps, and for the last, to recheck every binary, library and every type of system and vendor apps to see is something there in their code that will trigger that type of security mehanism (if any) to delete them

It will take so much time and patience but it could be worth it - but I'm not sure that you would have all legal rights to distribute such custom GApps in public. All their APIs is copyright protected by them and messing up with that could lead to serious legal actions.


Good luck ✨✨✨
